FinalMagayaApi/Controllers/EmbarquesController.cs
using Logica;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FinalMagayaApi.Controllers
{
    public class EmbarquesController : Controller
    {
        private WR _wrLogic = new WR();
        // GET: Embarques
        public ActionResult Index()
        {
            return View(_wrLogic.ListaWR());
        }

        public JsonResult GetbyID(int ID)
        {
           //WR datosWE = new WR();

           // var datos = datosWE.listaWRById(ID);


            return Json(true, JsonRequestBehavior.AllowGet);
        }
        public JsonResult ListPending()
        {
            WR datosWE = new WR();

            var datos = datosWE.ListaWR();
            return Json(datos, JsonRequestBehavior.AllowGet);
        }


        public ActionResult Pendientes()
        {
            //WR datosWE = new WR();

            //var datos = datosWE.listaWR();
            return View();
        }

        public ActionResult Transito()
        {
            return View();
        }

        public ActionResult Historial()
        {
            return View();
        }
        public ActionResult Rastreo()
        {
            return View();
        }
    }
}

FinalMagayaApi/Controllers/UserController.cs
using Data;
using Data.ViewModels;
using Logica;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace FinalMagayaApi.Controllers
{
    public class UserController : Controller
    {
        private UsuarioLogic ul = new UsuarioLogic();
        private DireccionesLogic dl = new DireccionesLogic();

        // GET: User
        [Authorize]
        public ActionResult Index()
        {
            return View(ul.ObtenerUsuarioSesion(((User).Identity).Name));
        }
        [Authorize]
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View(dl.DireccionxId(id));
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(DireccionesViewModel direccion)
        {
            dl.UpdateDireccion(direccion);
            return View(ul.ObtenerUsuarioSesion(((User).Identity).Name));
        }







        public JsonResult GetbyID(int ID)
        {

            return Json(dl.DireccionxId(ID), JsonRequestBehavior.AllowGet);
        }
        //public JsonResult Update(Employee emp)
        //{
        //    return Json(empDB.Update(emp), JsonRequestBehavior.AllowGet);
        //}
        //public JsonResult Delete(int ID)
        //{
        //    return Json(empDB.Delete(ID), JsonRequestBehavior.AllowGet);
        //}
    }
}

FinalMagayaApi/Views/Shared/_Addresses.cshtml
asdasdas

FinalMagayaApi/Views/Shared/_DashBoardTope.cshtml
<table style="background-color: #00a99d; border:1; width: 100%;">
    <tr>
        <td style="width:75px; left:10px; clip:rect(10px, auto, auto, 10px); text-align:center;">&nbsp;</td>
        <td width=75px;>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td style="width:75px; left:10px; clip:rect(20px, auto, auto, 10px); text-align:center;"><i class="fa fa-desktop fa-4x" style="color: #FFF;"></i></td>
        <td colspan="2" class="titulos">DashBoard</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td width="75px;">&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td colspan="3" style=" left:10px; clip:rect(20px, auto, auto, 10px); text-align:right;"> </td>
    </tr>
</table>

FinalMagayaApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="images/favicon.ico" type="image/ico" />

    <title>LTX | </title>

    <!-- Bootstrap -->
    <link href="~/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="~/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="~/vendors/nprogress/nprogress.css" rel="stylesheet">
    <!-- iCheck -->
    <link href="~/vendors/iCheck/skins/flat/green.css" rel="stylesheet">

    <!-- bootstrap-progressbar -->
    <link href="~/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
    <!-- JQVMap -->
    <link href="~/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />
    <!-- bootstrap-daterangepicker -->
    <link href="~/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="~/build/css/custom.min.css" rel="stylesheet">
</head>

<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="index.html" class="site_title"><span>LTX Tracking App</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <!-- menu profile quick info -->
                    @Html.Partial("_profileHome")
                    <!-- /menu profile quick info -->
                    <br />
                    <!-- sidebar menu -->
                    @Html.Partial("_navbar")
                </div>
            </div>
            <!-- top navigation -->
            @Html.Partial("_topNavbar")
            <!-- /top navigation -->
            @RenderBody()
            <!-- footer content -->
            @Html.Partial("_pie")
            <!-- /footer content -->
        </div>
    </div>

    <!-- jQuery -->
    <script src="~/vendors/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/vendors/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <!-- FastClick -->
    <script src="~/vendors/fastclick/lib/fastclick.js"></script>
    <!-- NProgress -->
    <script src="~/vendors/nprogress/nprogress.js"></script>
    <!-- Chart.js -->
    <script src="~/vendors/Chart.js/dist/Chart.min.js"></script>
    <!-- gauge.js -->
    <script src="~/vendors/gauge.js/dist/gauge.min.js"></script>
    <!-- bootstrap-progressbar -->
    <script src="~/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <!-- iCheck -->
    <script src="~/vendors/iCheck/icheck.min.js"></script>
    <!-- Skycons -->
    <script src="~/vendors/skycons/skycons.js"></script>
    <!-- Flot -->
    <script src="~/vendors/Flot/jquery.flot.js"></script>
    <script src="~/vendors/Flot/jquery.flot.pie.js"></script>
    <script src="~/vendors/Flot/jquery.flot.time.js"></script>
    <script src="~/vendors/Flot/jquery.flot.stack.js"></script>
    <script src="~/vendors/Flot/jquery.flot.resize.js"></script>
    <!-- Flot plugins -->
    <script src="~/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
    <script src="~/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
    <script src="~/vendors/flot.curvedlines/curvedLines.js"></script>
    <!-- DateJS -->
    <script src="~/vendors/DateJS/build/date.js"></script>
    <!-- JQVMap -->
    <script src="~/vendors/jqvmap/dist/jquery.vmap.js"></script>
    <script src="~/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
    <script src="~/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
    <!-- bootstrap-daterangepicker -->
    <script src="~/vendors/moment/min/moment.min.js"></script>
    <script src="~/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>

    <!-- Custom Theme Scripts -->


    <script src="~/build/js/custom.min.js"></script>



    <script src="~/vendors/bootstrap/dist/js/bootstrap.js"></script>
    <link href="~/vendors/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

    <script src="~/Scripts/employee.js"></script>
</body>
</html>

FinalMagayaApi/Views/Shared/_ScriptsView.cshtml
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<!-- Meta, title, CSS, favicons, etc. -->
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>LTX | </title>

<!-- Bootstrap -->
<link href="~/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
<link href="~/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="~/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<!-- NProgress -->
<link href="~/vendors/nprogress/nprogress.css" rel="stylesheet">
<!-- iCheck -->
<link href="~/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
<!-- bootstrap-wysiwyg -->
<link href="~/vendors/google-code-prettify/bin/prettify.min.css" rel="stylesheet">
<!-- Select2 -->
<link href="~/vendors/select2/dist/css/select2.min.css" rel="stylesheet">
<!-- Switchery -->
<link href="~/vendors/switchery/dist/switchery.min.css" rel="stylesheet">
<!-- starrr -->
<link href="~/vendors/starrr/dist/starrr.css" rel="stylesheet">
<!-- bootstrap-daterangepicker -->
<link href="~/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">

<!-- Custom Theme Style -->
<link href="~/build/css/custom.min.css" rel="stylesheet">

FinalMagayaApi/Views/Shared/_header.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>...::: LatamCargoXpress :::...</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Theme CSS -->
    <link href="~/css/freelancer.min.css" rel="stylesheet" />

    <!-- Custom Fonts -->
    <link href="~/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/css/bootstrap-dialog.min.css">



    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link href="~/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />

    <!-- Theme style -->
    <link href="~/assets/css/adminlte.min.css" rel="stylesheet" />





    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/js/bootstrap-dialog.min.js"></script>

    <script src="~/dist/sweetalert.min.js"></script>

    <link href="~/dist/sweetalert.css" rel="stylesheet" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    <script src="http://code.jquery.com/jquery-2.1.3.min.js"></script>

    <script type="text/javascript">

        $(window).load(function () {
            $("#loadPage").delay(5000).fadeOut("slow");




        });
    </script>

    <style type="text/css">
        #loadPage {
            display: block;
            background: #333;
            color: white;
            width: 100%;
            height: 100%;
            position: fixed;
            top: 0;
            left: 0;
            z-index: 1000;
        }

            #loadPage p {
                display: block;
                width: 800px;
                height: 30px;
                font-size: 30px;
                position: absolute;
                top: 0;
                left: 0;
                bottom: 0;
                right: 0;
                margin: auto;
            }
    </style>


    <script type="text/javascript">
        var divState = {}; // we store the status in this object
        function showhide(id) {
            if (document.getElementById) {
                var divid = document.getElementById(id);
                divState[id] = (divState[id]) ? false : true; // initialize / invert status (true is visible and false is closed)
                //close others
                for (var div in divState) {
                    if (divState[div] && div != id) { // ignore closed ones and the current
                        document.getElementById(div).style.display = 'none'; // hide
                        divState[div] = false; // reset status
                    }
                }
                divid.style.display = (divid.style.display == 'block' ? 'none' : 'block');
            }
        }
    </script>
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-92320907-1', 'auto');
        ga('send', 'pageview');
    </script>
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>
<body id="page-top" class="index" onload="myFunction()">
    <img src="~/assets/img/bg_general.jpg" id="full-screen-background-image" />


    <!-- Navigation -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    <img src="~/assets/img/logoLTX.png" width="103" height="32" />
                </a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Embarques Pendientes", "Pendientes", "Embarques")</li>
                    <li>@Html.ActionLink("Embarques en Tr&aacute;nsito", "Transito", "Embarques")</li>
                    <li>@Html.ActionLink("Historial", "Historial", "Embarques")</li>

                    <li><a href="rastreo.php">Rastreo</a> </li>
                    <li><a href="faq.php">FAQ</a> </li>
                    <li>@Html.ActionLink("Mi Cuenta", "Index", "User")</li>
                    <li><a href="cerrarSesion.php">Salir</a> </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="#">
                            <i class="fa fa-lock" aria-hidden="true"></i> @HttpContext.Current.User.Identity.Name
                        </a>

                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 col-lg-12">
                @ViewContext.RouteData.Values["controller"].ToString().ToLower()
                @if (ViewContext.RouteData.Values["controller"].ToString().ToLower() != "home")
                {
                    <ol class="breadcrumb">
                        <li>
                            @Html.ActionLink("Home", "Index", "Home")
                        </li>
                        <li>
                            @Html.ActionLink(ViewContext.RouteData.Values["controller"].ToString(), "Index")
                        </li>
                        <li class="active">
                            @Html.ActionLink(ViewContext.RouteData.Values["action"].ToString(), ViewContext.RouteData.Values["action"].ToString())
                        </li>
                    </ol>
                }
                <?php

                if ($pagina == "Embarques"){

                $hex = "#004c96";

                $imagen = "Images/calendar.png";

                $titulo = "Embarques Pendientes";

                }

                if ($pagina == "transito")

                {

                $hex = "#39b54a";

                $imagen = "Images/traffic.png";

                $titulo = "Embarques en Tr&aacute;nsito";

                }

                if ($pagina == "Historial")

                {

                $hex = "#93278f";

                $imagen = "Images/history.png";

                $titulo = "Historial";

                }

                if ($pagina == "Rastreo")

                {

                $hex = "#004698";

                $imagen = "Images/1469572681_18_radio_satellite_electric_wave_communication_space_spaceship_telescope_tracker.png";

                $titulo = "Rastreo";

                }

                if ($pagina == "Facturas")

                {

                $hex = "#f15a24";

                $imagen = "Images/facturas.png";

                $titulo = "Facturas";

                }

                if ($pagina == "cuenta")

                {

                $hex = "#7f7f7f";

                $imagen = "Images/1469572829_user_male2.png";

                $titulo = "Mi Cuenta";

                }



                if ($pagina == "puntos")

                {

                $hex = "#ed1c24";

                $imagen = "Images/1469573278_card_in_use.png";

                $titulo = "Puntos";

                }





                if ($pagina == "faq")

                {

                $hex = "#00a99d";

                $imagen = "Images/1469572919_faq.png";

                $titulo = "Preguntas Frecuentes";

                }





                if ($pagina == "dashboard")

                {

                $hex = "#00a99d";

                $imagen = "Images/1469572919_faq.png";

                $titulo = "DashBoard";

                }

                ?>

            <table style="background-color:  @ViewBag.Color; border: 1; width:100%;">
                <tr>
                    <td style="width:75px; left:10px; clip:rect(10px, auto, auto, 10px); text-align:center;">&nbsp;</td>
                    <td width=75px;>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td style="width:75px; left:10px; clip:rect(20px, auto, auto, 10px); text-align:center;">
                        <img src="~/assets/img/@ViewBag.Imagen"  width="52" height="52" />
                    </td>
                    <td colspan="2" class="titulos">@ViewBag.Titulo</td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td width="75px;">&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <tr>
                    <td colspan="3" style=" left:10px; clip:rect(20px, auto, auto, 10px); text-align:right;"> </td>
                </tr>
            </table>
            </div>
        </div>
    </nav>

FinalMagayaApi/Views/Shared/_mainsidebar.cshtml
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="~/assets/img/LogoLTX.png" class="brand-image img-circle elevation-3" style="opacity: .8"/>


        <span class="brand-text font-weight-light">LTX Track App</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel (optional) -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="info">
                <a href="#" class="d-block">@HttpContext.Current.User.Identity.Name</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                <li class="nav-item">




                    <a href="@Url.Action("Index", "Home")" class="nav-link">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Inicio
                        </p>
                    </a>


                </li>
                <li class="nav-item has-treeview">
                    <a href="@Url.Action("Index", "User")" class="nav-link">
                        <i class="nav-icon fas fa-table"></i>
                        <p>
                            Mi Cuenta
                        </p>
                    </a>

                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Pendientes", "Embarques")" class="nav-link">
                        <i class="nav-icon fas fa-th"></i>
                        <p>
                            Embarques Pendientes
                        </p>
                    </a>
                </li>
                <li class="nav-item">

                    <a href="@Url.Action("Transito", "Embarques")" class="nav-link">
                        <i class="nav-icon fas fa-copy"></i>
                        <p>
                            Embarques en Transito
                        </p>
                    </a>

                </li>

                <li class="nav-item">
                    <a href="@Url.Action("Historial", "Embarques")" class="nav-link">
                        <i class="nav-icon fas fa-chart-pie"></i>
                        <p>
                            Historial
                        </p>
                    </a>

                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Rastreo", "Embarques")" class="nav-link">
                        <i class="nav-icon fas fa-tree"></i>
                        <p>
                            Rastreo
                        </p>
                    </a>

                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "FAQ")" class="nav-link">
                        <i class="nav-icon fas fa-edit"></i>
                        <p>
                            FAQ
                        </p>
                    </a>
                </li>




            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

FinalMagayaApi/Views/Shared/_navbar.cshtml
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
            <li>
                <a href="@Url.Action("Index", "Home")" class="nav-link"><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
            </li>
            <li>
                <a href="@Url.Action("Index", "User")" class="nav-link"><i class="fa fa-user"></i> Mis Datos <span class="fa fa-chevron-down"></span></a>
            </li>

            <li>
                <a href="@Url.Action("Pendientes", "Embarques")" class="nav-link"><i class="fa fa-edit"></i> Embarques Pendientes <span class="fa fa-chevron-down"></span></a>
            </li>
            <li>
                <a href="@Url.Action("Transito", "Embarques")" class="nav-link"><i class="fa fa-desktop"></i> Embarques en Transito <span class="fa fa-chevron-down"></span></a>
            </li>
            <li>
                <a href="@Url.Action("Historial", "Embarques")" class="nav-link"><i class="fa fa-table"></i> Historial <span class="fa fa-chevron-down"></span></a>
            </li>
            <li>
                <a href="@Url.Action("Rastreo", "Embarques")" class="nav-link"><i class="fa fa-bar-chart-o"></i> Rastreo <span class="fa fa-chevron-down"></span></a>
            </li>
            <li>
                <a href="@Url.Action("Index", "FAQ")" class="nav-link"><i class="fa fa-clone"></i>FAQ <span class="fa fa-chevron-down"></span></a>
            </li>

        </ul>
    </div>
</div>

FinalMagayaApi/Views/Shared/_pie.cshtml
<footer>
    <div class="pull-right">
        Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
    </div>
    <div class="clearfix"></div>
</footer>

FinalMagayaApi/Views/Shared/_profileHome.cshtml
<div class="profile clearfix">
    <div class="profile_pic">
        <img src="images/img.jpg" alt="..." class="img-circle profile_img">
    </div>
    <div class="profile_info">
        <span>Welcome,</span>
        <h2>John Doe</h2>
    </div>
</div>